- name: Deploy to Server
        run: |
          if [ ! -d "devops-rj" ]; then
            git clone https://github.com/RAJATRAJPUT89-cmd/devops-rj.git
            cd devops-rj
          else
            cd devops-rj
            git pull
          fi
          docker build -t my-site .
          docker stop my-site || true
          docker rm my-site || true
          docker run -d --name my-site -p 80:80 my-site
